version: 2

sources:
    - name: dbt
      database: ryan-99

      tables:
        - name: bronze_games_post_wide
        - name: bronze_games_wide
        - name: table_1
        - name: table_2